# Behaviour spec — written before implementation (BDD-first). Declarative style.
# An in-app Claude agent turns my PT's ~6-weekly plan email (prose + .docx attachments)
# into structured data. HARD RULE: the agent PROPOSES; Seth reviews/edits; then it commits.
# Carbs drive insulin dosing, so nothing medical-relevant is ever committed silently.

Feature: Plan ingestion by the AI agent
  As Seth, who gets a fresh plan from my PT roughly every 6 weeks,
  I want an agent to read the email and its attachments and set up my plan for me,
  so that re-planning costs me almost no admin — while I stay in control of what gets saved.

  Background:
    Given I am logged in
    And my PT has sent a new plan as an email with .docx attachments
      | attachment    |
      | Day 1 of 3    |
      | Day 2 of 3    |
      | Day 3 of 3    |
      | Mobility      |

  # --- Extraction ---

  Scenario: The agent proposes a structured plan from the email and attachments
    When the ingestion agent processes the email and attachments
    Then it proposes training days with exercises and sets × reps
    And it proposes a mobility round
    And it proposes the daily meals with their macros
    And it proposes the daily targets (steps, water, electrolytes, macros)
    And nothing is saved yet

  Scenario: The agent parses the Word-document attachments
    Given each training day is laid out as an exercise table inside a .docx
    When the ingestion agent processes the attachments
    Then each day's exercises, sets × reps, and prescribed weights are extracted

  Scenario: Guidance and context are retained, not just numbers
    Given the email contains non-negotiables and shoulder-training guidance
    When the plan is committed
    Then that guidance is stored alongside the plan for reference

  # --- Human-in-the-loop (the hard rule) ---

  Scenario: Nothing is committed until I approve it
    When the agent has produced a proposal
    Then my current active plan is unchanged
    And the proposal becomes my active plan only after I approve it

  Scenario: I can edit the proposal before committing
    Given a proposed plan where "Meal 1 — Breakfast" reads 74 g carbs
    When I correct it to 72 g carbs
    And I approve the plan
    Then the active plan stores 72 g carbs for "Meal 1 — Breakfast"

  Scenario: Every meal's carbs are surfaced for explicit confirmation
    Given a proposed plan with per-meal carbs
    When I review the proposal
    Then each meal's carb figure is shown for me to confirm before commit

  Scenario: Low-confidence extractions are flagged, never guessed
    Given the agent cannot confidently read the prescribed weight for an exercise
    When I review the proposal
    Then that field is flagged for my attention
    And it is left empty rather than filled with a guess

  # --- Versioning (~6-week blocks) ---

  Scenario: Approving a new plan archives the previous one
    Given I have an active plan dated 2026-05-21
    When I approve a new plan dated 2026-07-02
    Then the new plan becomes current
    And the 2026-05-21 plan is archived and still readable
    And my logged sessions and sets against the old plan are preserved

  Scenario: The new plan drives the daily list from its start date
    Given I approve a new plan effective 2026-07-02
    When I open today's list on 2026-07-02
    Then the activities and meals come from the new plan

  # --- Derived outputs ---

  Scenario: A shopping list is generated from the plan's meals
    Given the plan's meals list their ingredients with quantities
    When the plan is committed
    Then a weekly shopping list is generated by aggregating those ingredients

  # --- Delivery: auto-pull from Gmail (with manual fallback) ---

  Scenario: A new plan email from my PT is detected and queued
    Given the app is connected to my Gmail
    When a plan email arrives from my PT with .docx attachments
    Then the app detects it and queues it for ingestion
    And its attachments are pulled in with it

  Scenario: Only my PT's plan emails are picked up
    Given the app is connected to my Gmail
    When an email arrives from someone other than my PT
    Then it is not queued for plan ingestion

  Scenario: Auto-pull removes the upload step, not the review step
    Given a plan email from my PT has been auto-pulled
    When the agent produces a proposal from it
    Then my active plan is unchanged until I approve it

  Scenario: A Gmail failure is surfaced, with manual upload as fallback
    Given the app cannot reach my Gmail
    When a new plan is expected
    Then the app tells me auto-pull is unavailable
    And I can upload the email and its attachments manually instead
