"""initial schema

Revision ID: 55ebeab3e818
Revises: 
Create Date: 2026-06-02 15:41:10.315655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ebeab3e818'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('worked_on', sa.Text(), nullable=True),
    sa.Column('struggles', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_started_on'), 'check_in', ['started_on'], unique=False)
    op.create_table('daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('water_units', sa.Integer(), nullable=False),
    sa.Column('electrolytes_done', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_log_date'), 'daily_log', ['date'], unique=True)
    op.create_table('daily_wellbeing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('hunger', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('energy IS NULL OR energy BETWEEN 1 AND 10', name='ck_energy_1_10'),
    sa.CheckConstraint('hunger IS NULL OR hunger BETWEEN 1 AND 10', name='ck_hunger_1_10'),
    sa.CheckConstraint('motivation IS NULL OR motivation BETWEEN 1 AND 10', name='ck_motivation_1_10'),
    sa.CheckConstraint('stress IS NULL OR stress BETWEEN 1 AND 10', name='ck_stress_1_10'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_wellbeing_date'), 'daily_wellbeing', ['date'], unique=True)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_bodyweight', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_slug'), 'exercise', ['slug'], unique=True)
    op.create_table('glucose_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mmol_l', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glucose_reading_ts'), 'glucose_reading', ['ts'], unique=False)
    op.create_table('insulin_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insulin_event_ts'), 'insulin_event', ['ts'], unique=False)
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('tummy_cm', sa.Float(), nullable=True),
    sa.Column('bum_cm', sa.Float(), nullable=True),
    sa.Column('right_thigh_cm', sa.Float(), nullable=True),
    sa.Column('left_thigh_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_date'), 'measurement', ['date'], unique=True)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('steps_target', sa.Integer(), nullable=True),
    sa.Column('water_min_l', sa.Float(), nullable=True),
    sa.Column('water_max_l', sa.Float(), nullable=True),
    sa.Column('electrolytes_per_day', sa.Integer(), nullable=True),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('daily_protein_g', sa.Integer(), nullable=True),
    sa.Column('daily_carbs_g', sa.Integer(), nullable=True),
    sa.Column('daily_fat_g', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_is_current'), 'plan', ['is_current'], unique=False)
    op.create_table('sleep_night',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.String(), nullable=True),
    sa.Column('wake_time', sa.String(), nullable=True),
    sa.Column('asleep_min', sa.Float(), nullable=True),
    sa.Column('in_bed_min', sa.Float(), nullable=True),
    sa.Column('awake_min', sa.Float(), nullable=True),
    sa.Column('light_min', sa.Float(), nullable=True),
    sa.Column('deep_min', sa.Float(), nullable=True),
    sa.Column('rem_min', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_night_date'), 'sleep_night', ['date'], unique=True)
    op.create_table('steps_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('target_steps', sa.Integer(), nullable=True),
    sa.Column('target_met', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_day_date'), 'steps_day', ['date'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('check_in_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_in.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_photo_check_in_id'), 'check_in_photo', ['check_in_id'], unique=False)
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_number', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('carbs_g', sa.Integer(), nullable=True),
    sa.Column('fat_g', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_id'), 'meal', ['plan_id'], unique=False)
    op.create_table('mobility_done',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'exercise_id', name='uq_mobility_done_day_ex')
    )
    op.create_index(op.f('ix_mobility_done_date'), 'mobility_done', ['date'], unique=False)
    op.create_index(op.f('ix_mobility_done_exercise_id'), 'mobility_done', ['exercise_id'], unique=False)
    op.create_table('shopping_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_plan_id'), 'shopping_list', ['plan_id'], unique=False)
    op.create_table('training_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_day_plan_id'), 'training_day', ['plan_id'], unique=False)
    op.create_table('meal_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('eaten', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'meal_id', name='uq_meal_check_day_meal')
    )
    op.create_index(op.f('ix_meal_check_date'), 'meal_check', ['date'], unique=False)
    op.create_index(op.f('ix_meal_check_meal_id'), 'meal_check', ['meal_id'], unique=False)
    op.create_table('meal_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_ingredient_meal_id'), 'meal_ingredient', ['meal_id'], unique=False)
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets_x_reps', sa.String(), nullable=False),
    sa.Column('prescribed_weight', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_exercise_id'), 'prescription', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_prescription_training_day_id'), 'prescription', ['training_day_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weekday', sa.String(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('training_day_id', sa.Integer(), nullable=True),
    sa.Column('bodyweight_kg', sa.Float(), nullable=True),
    sa.Column('pre_energy', sa.Integer(), nullable=True),
    sa.Column('shoulder_check', sa.Text(), nullable=True),
    sa.Column('how_it_felt', sa.Text(), nullable=True),
    sa.Column('what_to_change', sa.Text(), nullable=True),
    sa.Column('post_cardio_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_date'), 'session', ['date'], unique=False)
    op.create_table('shopping_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_item_shopping_list_id'), 'shopping_item', ['shopping_list_id'], unique=False)
    op.create_table('weekday_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(), nullable=False),
    sa.Column('training_day_id', sa.Integer(), nullable=True),
    sa.Column('has_mobility', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_day.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekday_schedule_plan_id'), 'weekday_schedule', ['plan_id'], unique=False)
    op.create_table('set_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_entry_exercise_id'), 'set_entry', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_set_entry_session_id'), 'set_entry', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_entry_session_id'), table_name='set_entry')
    op.drop_index(op.f('ix_set_entry_exercise_id'), table_name='set_entry')
    op.drop_table('set_entry')
    op.drop_index(op.f('ix_weekday_schedule_plan_id'), table_name='weekday_schedule')
    op.drop_table('weekday_schedule')
    op.drop_index(op.f('ix_shopping_item_shopping_list_id'), table_name='shopping_item')
    op.drop_table('shopping_item')
    op.drop_index(op.f('ix_session_date'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_prescription_training_day_id'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_exercise_id'), table_name='prescription')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_meal_ingredient_meal_id'), table_name='meal_ingredient')
    op.drop_table('meal_ingredient')
    op.drop_index(op.f('ix_meal_check_meal_id'), table_name='meal_check')
    op.drop_index(op.f('ix_meal_check_date'), table_name='meal_check')
    op.drop_table('meal_check')
    op.drop_index(op.f('ix_training_day_plan_id'), table_name='training_day')
    op.drop_table('training_day')
    op.drop_index(op.f('ix_shopping_list_plan_id'), table_name='shopping_list')
    op.drop_table('shopping_list')
    op.drop_index(op.f('ix_mobility_done_exercise_id'), table_name='mobility_done')
    op.drop_index(op.f('ix_mobility_done_date'), table_name='mobility_done')
    op.drop_table('mobility_done')
    op.drop_index(op.f('ix_meal_plan_id'), table_name='meal')
    op.drop_table('meal')
    op.drop_index(op.f('ix_check_in_photo_check_in_id'), table_name='check_in_photo')
    op.drop_table('check_in_photo')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_steps_day_date'), table_name='steps_day')
    op.drop_table('steps_day')
    op.drop_index(op.f('ix_sleep_night_date'), table_name='sleep_night')
    op.drop_table('sleep_night')
    op.drop_index(op.f('ix_plan_is_current'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_measurement_date'), table_name='measurement')
    op.drop_table('measurement')
    op.drop_index(op.f('ix_insulin_event_ts'), table_name='insulin_event')
    op.drop_table('insulin_event')
    op.drop_index(op.f('ix_glucose_reading_ts'), table_name='glucose_reading')
    op.drop_table('glucose_reading')
    op.drop_index(op.f('ix_exercise_slug'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_daily_wellbeing_date'), table_name='daily_wellbeing')
    op.drop_table('daily_wellbeing')
    op.drop_index(op.f('ix_daily_log_date'), table_name='daily_log')
    op.drop_table('daily_log')
    op.drop_index(op.f('ix_check_in_started_on'), table_name='check_in')
    op.drop_table('check_in')
    # ### end Alembic commands ###
